### ISSUE TITLE
Constantly (well, often) loosing data

### ISSUE THREAD

**Issue by kutenai** [duosecurity/duo_universal_atlassian#3]
Out company setup Duo with confluence server. Now, I'll have a document in process, and Duo will somehow decide it needs to 'updated' -- it does not even require me to login (I'll have already done that today), but when it does this, I loose all of my content in progress. There is no way to recover it!!

I've never lost content with Confluence before.. Is this a known issue? Is this a possible configuration issue? Is there a fix?????

**Comment by DuoKristina** [comment]
Hi @kutenai,

The draft saving behavior in Confluence changes depending on which options have been enabled. I found this article about it: https://confluence.atlassian.com/confkb/how-do-drafts-work-on-confluence-938043306.html.

We are unable to assist end users of Duo directly. Please get in touch with your organization's Confluence administrator to let them know about your issue. If they are unable to resolve it from the Confluence settings, and it is not a problem when Duo isn't installed, your organization's Duo administrator should contact [Duo Support](https://duo.com/support) for further assistance.

Thanks for raising this issue.
