### ISSUE TITLE
Provide IP whitelisting option for application link support

### ISSUE THREAD

**Issue by Nothing4You** [duosecurity/duo_universal_atlassian#4]
Now that https://github.com/duosecurity/duo_confluence/pull/7 is closed due to the repo being deprecated, let's continue this issue here.

I don't expect this to be ever resolved due to DUO apparently not caring enough about paying customers, considering that a solution for this issue has been presented almost 4 years ago and being rejected with
> Every hole we purposely make in the plugin creates that much more of a vulnerability.

while at the same time suggesting to
> bypass[es] Duo for all listed endpoints

in the official support article https://help.duo.com/s/article/1364, without the option of restricting that to IPs.

This is a crucial requirement to be able to use application links between applications securely without exposing endpoints without DUO to all other clients.

**Comment by BenGreenGDIT** [comment]
I'm at the same point with this issue. Confluence/Jira integration is broken. Is there a plan to support this with the Universal plugin, or should I discontinue using Duo for 2FA?

Thanks.

**Comment by AaronAtDuo** [comment]
Closing this issue due to repository deprecation and Atlassian end of support for its on-prem products.
