### ISSUE TITLE
Upgrade duo_universal_sdk to latest release

### ISSUE THREAD

**Issue by LevBernstein** [duosecurity/duo_universal_atlassian#5]
duo_seraph_filter/pom.xml includes duo_universal_sdk version 1.0.3 as a dependency. This version is quite out of date, and hosts some security vulnerabilities that I patched in a recent PR. We should bump duo_universal_sdk to the latest release; this is currently 1.1.3, though I'd suggest releasing 1.1.4 soon, given that 1.1.3 still contains security vulnerabilities.

**Comment by AaronAtDuo** [comment]
@LevBernstein I will look into this; but keep in mind that with support for on-prem Atlassian products ending soon (https://www.atlassian.com/migration/assess/journey-to-cloud) and our plugin not supported on cloud Atlassian, it's not clear if there's a future for this repo...

**Comment by AaronAtDuo** [comment]
Closing this issue due to repository deprecation and Atlassian end of support for its on-prem products.
